const { WEBHOOK_VERIFY_TOKEN, GRAPH_API_TOKEN, GEMINI_API_KEY, GEMINI_API_URL, PORT, META_URL, META_TOKEN, GRAPH_VERSION } = process.env;

module.exports = {
    WEBHOOK_VERIFY_TOKEN,
    GRAPH_API_TOKEN,
    GEMINI_API_KEY,
    GEMINI_API_URL,
    PORT,
    META_URL,
    META_TOKEN,
    GRAPH_VERSION
}